- config:
    algorithm:
      type: RFClassifier
      quality_metric: MCC
      indent_coeff: 0.25
    scrubber:
      type: linear
      window_length: 48
      shift_factor: 0.5
  distr_config:
    name: 0-exponential
    distributions:
    - type: exponential
      length: 48
      parameters:
        rate: 1.0
  optimal_values:
    threshold: 0.515625
- config:
    algorithm:
      type: RFClassifier
      quality_metric: MCC
      indent_coeff: 0.25
    scrubber:
      type: linear
      window_length: 48
      shift_factor: 0.5
  distr_config:
    name: 1-normal
    distributions:
    - type: normal
      length: 48
      parameters:
        mean: 0.0
        variance: 1.0
  optimal_values:
    threshold: 0.515625
- config:
    algorithm:
      type: RFClassifier
      quality_metric: MCC
      indent_coeff: 0.25
    scrubber:
      type: linear
      window_length: 48
      shift_factor: 0.5
  distr_config:
    name: 2-uniform
    distributions:
    - type: uniform
      length: 48
      parameters:
        min: 0.0
        max: 1.0
  optimal_values:
    threshold: 0.515625
- config:
    algorithm:
      type: RFClassifier
      quality_metric: MCC
      indent_coeff: 0.25
    scrubber:
      type: linear
      window_length: 48
      shift_factor: 0.5
  distr_config:
    name: 3-beta
    distributions:
    - type: beta
      length: 48
      parameters:
        alpha: 1.0
        beta: 1.0
  optimal_values:
    threshold: 0.515625
- config:
    algorithm:
      type: RFClassifier
      quality_metric: MCC
      indent_coeff: 0.25
    scrubber:
      type: linear
      window_length: 48
      shift_factor: 0.5
  distr_config:
    name: 4-weibull
    distributions:
    - type: weibull
      length: 48
      parameters:
        shape: 0.5
        scale: 1.0
  optimal_values:
    threshold: 0.515625
- config:
    algorithm:
      type: RFClassifier
      quality_metric: MCC
      indent_coeff: 0.25
    scrubber:
      type: linear
      window_length: 48
      shift_factor: 0.5
  distr_config:
    name: 5-weibull
    distributions:
    - type: weibull
      length: 48
      parameters:
        shape: 1.0
        scale: 1.0
  optimal_values:
    threshold: 0.515625
- config:
    algorithm:
      type: RFClassifier
      quality_metric: MCC
      indent_coeff: 0.25
    scrubber:
      type: linear
      window_length: 48
      shift_factor: 0.5
  distr_config:
    name: 6-weibull
    distributions:
    - type: weibull
      length: 48
      parameters:
        shape: 2.0
        scale: 1.0
  optimal_values:
    threshold: 0.515625
- config:
    algorithm:
      type: RFClassifier
      quality_metric: MCC
      indent_coeff: 0.25
    scrubber:
      type: linear
      window_length: 48
      shift_factor: 0.5
  distr_config:
    name: 0-multivariate_normal
    distributions:
    - type: multivariate_normal
      length: 48
      parameters:
        mean: '["0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]'
  optimal_values:
    threshold: 0.5625
- config:
    algorithm:
      type: RFClassifier
      quality_metric: MCC
      indent_coeff: 0.25
    scrubber:
      type: linear
      window_length: 48
      shift_factor: 0.5
  distr_config:
    name: 1-multivariate_normal
    distributions:
    - type: multivariate_normal
      length: 48
      parameters:
        mean: '["0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]'
  optimal_values:
    threshold: 0.515625
- config:
    algorithm:
      type: RFClassifier
      quality_metric: MCC
      indent_coeff: 0.25
    scrubber:
      type: linear
      window_length: 48
      shift_factor: 0.5
  distr_config:
    name: 2-multivariate_normal
    distributions:
    - type: multivariate_normal
      length: 48
      parameters:
        mean: '["0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
          "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]'
  optimal_values:
    threshold: 0.4921875
