- name: example
  distributions:
    - type: exponential
      length: 200
      parameters:
        rate: 2.0
    - type: beta
      length: 200
      parameters:
        alpha:  1.0
        beta:  5.0
    - type: uniform
      length: 200
      parameters:
        min: 0
        max: 0.5
